//
// RsearchAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class RsearchAPI {
    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter docId: () Document ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addDocument(indexName: StringdocTypeName: StringdocId: Stringcompletion: @escaping ((_ data: CreateDocumentSuccess?,_ error: Error?) -> Void)) {
        addDocumentWithRequestBuilder(indexName: indexNamedocTypeName: docTypeNamedocId: docId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /indexes/{index_name}/document_types/{doc_type_name}/documents/{doc_id}
     - Creates `doc_id` in `doc_type_name` for `index_name`
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: writeAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter docId: () Document ID 

     - returns: RequestBuilder<CreateDocumentSuccess> 
     */
    open class func addDocumentWithRequestBuilder(indexName: StringdocTypeName: StringdocId: String) -> RequestBuilder<CreateDocumentSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/documents/{doc_id}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_id}", with: "\(docId)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CreateDocumentSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addDocumentType(indexName: StringdocTypeName: Stringcompletion: @escaping ((_ data: CreateDocTypeSuccess?,_ error: Error?) -> Void)) {
        addDocumentTypeWithRequestBuilder(indexName: indexNamedocTypeName: docTypeName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /indexes/{index_name}/document_types/{doc_type_name}
     - Creates specific `document_type` in `index_name` with specified parameters. You should define the parameters correctly as per the getting started guide, else getting the right structure might be an issue.
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 

     - returns: RequestBuilder<CreateDocTypeSuccess> 
     */
    open class func addDocumentTypeWithRequestBuilder(indexName: StringdocTypeName: String) -> RequestBuilder<CreateDocTypeSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CreateDocTypeSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addIndex(indexName: Stringcompletion: @escaping ((_ data: CreateIndexSuccess?,_ error: Error?) -> Void)) {
        addIndexWithRequestBuilder(indexName: indexName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /indexes/{index_name}
     - Creates `a new index`.
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: writeAppID
     - parameter indexName: () Name of the index 

     - returns: RequestBuilder<CreateIndexSuccess> 
     */
    open class func addIndexWithRequestBuilder(indexName: String) -> RequestBuilder<CreateIndexSuccess> {
        var path = "/indexes/{index_name}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CreateIndexSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter docId: () Document ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteDocument(indexName: StringdocTypeName: StringdocId: Stringcompletion: @escaping ((_ data: DeleteDocumentSuccess?,_ error: Error?) -> Void)) {
        deleteDocumentWithRequestBuilder(indexName: indexNamedocTypeName: docTypeNamedocId: docId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - DELETE /indexes/{index_name}/document_types/{doc_type_name}/documents/{doc_id}
     - Deletes `doc_id` in `doc_type_name` for `index_name`
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: writeAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter docId: () Document ID 

     - returns: RequestBuilder<DeleteDocumentSuccess> 
     */
    open class func deleteDocumentWithRequestBuilder(indexName: StringdocTypeName: StringdocId: String) -> RequestBuilder<DeleteDocumentSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/documents/{doc_id}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_id}", with: "\(docId)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeleteDocumentSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteIndex(indexName: Stringcompletion: @escaping ((_ data: DeleteIndexSuccess?,_ error: Error?) -> Void)) {
        deleteIndexWithRequestBuilder(indexName: indexName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - DELETE /indexes/{index_name}
     - Deletes `an index` {index_name}
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: writeAppID
     - parameter indexName: () Name of the index 

     - returns: RequestBuilder<DeleteIndexSuccess> 
     */
    open class func deleteIndexWithRequestBuilder(indexName: String) -> RequestBuilder<DeleteIndexSuccess> {
        var path = "/indexes/{index_name}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<DeleteIndexSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the Document_type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAdvancedDocTypeSuggestResults(indexName: StringdocTypeName: Stringcompletion: @escaping ((_ data: SuggestSuccess?,_ error: Error?) -> Void)) {
        getAdvancedDocTypeSuggestResultsWithRequestBuilder(indexName: indexNamedocTypeName: docTypeName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /indexes/{index_name}/document_types/{doc_type_name}/suggest
     - Gets Suggestions from `doc_type_name` in `index_name` limited by the body params. Please ensure you refer the getting started guides, to get the format of the query right.
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the Document_type 

     - returns: RequestBuilder<SuggestSuccess> 
     */
    open class func getAdvancedDocTypeSuggestResultsWithRequestBuilder(indexName: StringdocTypeName: String) -> RequestBuilder<SuggestSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/suggest"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SuggestSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAdvancedIndexSuggestResults(indexName: Stringcompletion: @escaping ((_ data: SuggestSuccess?,_ error: Error?) -> Void)) {
        getAdvancedIndexSuggestResultsWithRequestBuilder(indexName: indexName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /indexes/{index_name}/suggest
     - Gets Suggestions in `index_name` limited by the request body fields
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 

     - returns: RequestBuilder<SuggestSuccess> 
     */
    open class func getAdvancedIndexSuggestResultsWithRequestBuilder(indexName: String) -> RequestBuilder<SuggestSuccess> {
        var path = "/indexes/{index_name}/suggest"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SuggestSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the Document_type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAdvancedSearchResults(indexName: StringdocTypeName: Stringcompletion: @escaping ((_ data: SearchSuccess?,_ error: Error?) -> Void)) {
        getAdvancedSearchResultsWithRequestBuilder(indexName: indexNamedocTypeName: docTypeName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /indexes/{index_name}/document_types/{doc_type_name}/search
     - Advanced Search which gets all documents in `index_name` for provided search criteria. Please ensure you refer the getting started guides, to get the format of the query right.
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: writeAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the Document_type 

     - returns: RequestBuilder<SearchSuccess> 
     */
    open class func getAdvancedSearchResultsWithRequestBuilder(indexName: StringdocTypeName: String) -> RequestBuilder<SearchSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/search"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SearchSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAllDocumentTypes(indexName: Stringcompletion: @escaping ((_ data: GetDocTypesSuccess?,_ error: Error?) -> Void)) {
        getAllDocumentTypesWithRequestBuilder(indexName: indexName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}/document_types
     - Gets `All document_types` present in `index_name`
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 

     - returns: RequestBuilder<GetDocTypesSuccess> 
     */
    open class func getAllDocumentTypesWithRequestBuilder(indexName: String) -> RequestBuilder<GetDocTypesSuccess> {
        var path = "/indexes/{index_name}/document_types"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetDocTypesSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAllDocuments(indexName: StringdocTypeName: Stringcompletion: @escaping ((_ data: GetDocumentsSuccess?,_ error: Error?) -> Void)) {
        getAllDocumentsWithRequestBuilder(indexName: indexNamedocTypeName: docTypeName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}/document_types/{doc_type_name}/documents
     - Fetches all documents in `doc_type_name` for `index_name`. All the documents and hence careful with its use.
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 

     - returns: RequestBuilder<GetDocumentsSuccess> 
     */
    open class func getAllDocumentsWithRequestBuilder(indexName: StringdocTypeName: String) -> RequestBuilder<GetDocumentsSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/documents"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetDocumentsSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAllIndexes(completion: @escaping ((_ data: GetIndexesSuccess?,_ error: Error?) -> Void)) {
        getAllIndexesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes
     - Fetches `All indexes` that the user has. Not recommended to be used in production code, as there isn't that big a Use case for listing all indexes!
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID

     - returns: RequestBuilder<GetIndexesSuccess> 
     */
    open class func getAllIndexesWithRequestBuilder() -> RequestBuilder<GetIndexesSuccess> {
        let path = "/indexes"
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetIndexesSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter q: () Search Query 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBasicSearchResults(indexName: Stringq: Stringcompletion: @escaping ((_ data: SearchSuccess?,_ error: Error?) -> Void)) {
        getBasicSearchResultsWithRequestBuilder(indexName: indexNameq: q).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}/search
     - Basic Search which gets all documents in `index_name` for provided search criteria
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter q: () Search Query 

     - returns: RequestBuilder<SearchSuccess> 
     */
    open class func getBasicSearchResultsWithRequestBuilder(indexName: Stringq: String) -> RequestBuilder<SearchSuccess> {
        var path = "/indexes/{index_name}/search"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "q": q
        ])
        

        let requestBuilder: RequestBuilder<SearchSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the Document_type 
     - parameter q: () Details of the suggest query 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDocTypeSuggestResults(indexName: StringdocTypeName: Stringq: Stringcompletion: @escaping ((_ data: SuggestSuccess?,_ error: Error?) -> Void)) {
        getDocTypeSuggestResultsWithRequestBuilder(indexName: indexNamedocTypeName: docTypeNameq: q).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}/document_types/{doc_type_name}/suggest
     - Gets Suggestions from `doc_type_name` in `index_name`. Please ensure you refer the getting started guides, to get the format of the query right.
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the Document_type 
     - parameter q: () Details of the suggest query 

     - returns: RequestBuilder<SuggestSuccess> 
     */
    open class func getDocTypeSuggestResultsWithRequestBuilder(indexName: StringdocTypeName: Stringq: String) -> RequestBuilder<SuggestSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/suggest"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "q": q
        ])
        

        let requestBuilder: RequestBuilder<SuggestSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter docId: () Document ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDocument(indexName: StringdocTypeName: StringdocId: Stringcompletion: @escaping ((_ data: GetDocumentSuccess?,_ error: Error?) -> Void)) {
        getDocumentWithRequestBuilder(indexName: indexNamedocTypeName: docTypeNamedocId: docId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}/document_types/{doc_type_name}/documents/{doc_id}
     - Fetches the document referenced by `doc_id` in `doc_type_name` for `index_name`
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter docId: () Document ID 

     - returns: RequestBuilder<GetDocumentSuccess> 
     */
    open class func getDocumentWithRequestBuilder(indexName: StringdocTypeName: StringdocId: String) -> RequestBuilder<GetDocumentSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}/documents/{doc_id}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_id}", with: "\(docId)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetDocumentSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDocumentType(indexName: StringdocTypeName: Stringcompletion: @escaping ((_ data: GetDocTypeSuccess?,_ error: Error?) -> Void)) {
        getDocumentTypeWithRequestBuilder(indexName: indexNamedocTypeName: docTypeName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}/document_types/{doc_type_name}
     - Checks whether `document_type` in `index_name` exists
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 
     - parameter docTypeName: () Name of the document_type 

     - returns: RequestBuilder<GetDocTypeSuccess> 
     */
    open class func getDocumentTypeWithRequestBuilder(indexName: StringdocTypeName: String) -> RequestBuilder<GetDocTypeSuccess> {
        var path = "/indexes/{index_name}/document_types/{doc_type_name}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        path = path.replacingOccurrences(of: "{doc_type_name}", with: "\(docTypeName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetDocTypeSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter indexName: () Name of the index 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getIndex(indexName: Stringcompletion: @escaping ((_ data: GetIndexSuccess?,_ error: Error?) -> Void)) {
        getIndexWithRequestBuilder(indexName: indexName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /indexes/{index_name}
     - Checks whether `a particular index` {index_name} exists
     - :
       - type: apiKey auth_token 
       - name: authToken
     - :
       - type: apiKey X-RSearch-App-ID 
       - name: readAppID
     - parameter indexName: () Name of the index 

     - returns: RequestBuilder<GetIndexSuccess> 
     */
    open class func getIndexWithRequestBuilder(indexName: String) -> RequestBuilder<GetIndexSuccess> {
        var path = "/indexes/{index_name}"
        path = path.replacingOccurrences(of: "{index_name}", with: "\(indexName)", options: .literal, range: nil)
        let URLString = RSearchClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<GetIndexSuccess>.Type = RSearchClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
