//
// AlgorithmSuccess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AlgorithmSuccess: Codable {

    public var algorithmResults: AlgorithmSuccessAlgorithmResults


    
    public init(algorithmResults: AlgorithmSuccessAlgorithmResults) {
        self.algorithmResults = algorithmResults
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(algorithmResults, forKey: "algorithm_results")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        algorithmResults = try container.decode(AlgorithmSuccessAlgorithmResults.self, forKey: "algorithm_results")
    }
}

