//
// CreateDocTypeSuccess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CreateDocTypeSuccess: Codable {

    public var documentType: CreateIndexSuccessIndexes


    
    public init(documentType: CreateIndexSuccessIndexes) {
        self.documentType = documentType
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(documentType, forKey: "document_type")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        documentType = try container.decode(CreateIndexSuccessIndexes.self, forKey: "document_type")
    }
}

