//
// CreateIndexSuccessIndexes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CreateIndexSuccessIndexes: Codable {

    public enum Result: String, Codable { 
        case created = "created"
    }
    public var result: Result


    
    public init(result: Result) {
        self.result = result
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(result, forKey: "result")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        result = try container.decode(Result.self, forKey: "result")
    }
}

