//
// DeleteDocumentSuccess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DeleteDocumentSuccess: Codable {

    public var document: DeleteIndexSuccessIndex


    
    public init(document: DeleteIndexSuccessIndex) {
        self.document = document
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(document, forKey: "document")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        document = try container.decode(DeleteIndexSuccessIndex.self, forKey: "document")
    }
}

