//
// DoctypesFailure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class DoctypesFailure: Codable {

    public var documentTypes: InlineResponse400Indexes?

    public init() {}

}
