//
// Document.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Document: Codable {

    public var documentId: String
    public var fields: [Any]


    
    public init(documentId: String, fields: [Any]) {
        self.documentId = documentId
        self.fields = fields
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(documentId, forKey: "document_id")
        try container.encode(fields, forKey: "fields")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        documentId = try container.decode(String.self, forKey: "document_id")
        fields = try container.decode([Any].self, forKey: "fields")
    }
}

