//
// GetAllDoctypesSuccess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class GetAllDoctypesSuccess: Codable {

    public var indexes: InlineResponse2002Indexes?

    public init() {}

}
