//
// GetDoctypeSuccess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class GetDoctypeSuccess: Codable {

    public var documentType: InlineResponse2003DocumentType?

    public init() {}

}
