//
// IndexesSuggestQuerySuggest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class IndexesSuggestQuerySuggest: Codable {

    public var query: String
    public var indexes: [String]
    public var fields: [String]
    public var fuzzy: Double?
    public var size: Double?


    
    public init(query: String, indexes: [String], fields: [String], fuzzy: Double?, size: Double?) {
        self.query = query
        self.indexes = indexes
        self.fields = fields
        self.fuzzy = fuzzy
        self.size = size
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(query, forKey: "query")
        try container.encode(indexes, forKey: "indexes")
        try container.encode(fields, forKey: "fields")
        try container.encodeIfPresent(fuzzy, forKey: "fuzzy")
        try container.encodeIfPresent(size, forKey: "size")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        query = try container.decode(String.self, forKey: "query")
        indexes = try container.decode([String].self, forKey: "indexes")
        fields = try container.decode([String].self, forKey: "fields")
        fuzzy = try container.decodeIfPresent(Double.self, forKey: "fuzzy")
        size = try container.decodeIfPresent(Double.self, forKey: "size")
    }
}

