//
// IndexesSearchQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class IndexesSearchQuery: Codable {

    public var search: IndexesSearchQuerySearch


    
    public init(search: IndexesSearchQuerySearch) {
        self.search = search
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(search, forKey: "search")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        search = try container.decode(IndexesSearchQuerySearch.self, forKey: "search")
    }
}

