//
// InlineResponse2002Indexes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2002Indexes: Codable {

    public var results: [ERRORUNKNOWN]?
    public var metadata: Any?

    public init() {}

}
