//
// InlineResponse2008.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2008: Codable {

    public var suggestResults: InlineResponse2008SuggestResults?

    public init() {}

}
