//
// InlineResponse2004.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2004: Codable {

    public var document: InlineResponse2004Document?

    public init() {}

}
