//
// InlineResponse202.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse202: Codable {

    public var index: InlineResponse202Index?

    public init() {}

}
