//
// InlineResponse2005.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2005: Codable {

    public var document: InlineResponse201Index?

    public init() {}

}
