//
// InlineResponse2003DocumentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2003DocumentType: Codable {

    public var result: Any?

    public init() {}

}
