//
// InlineResponse4003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4003: Codable {

    public var documentType: InlineResponse400Indexes?

    public init() {}

}
