//
// InlineResponse2006.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2006: Codable {

    public var document: InlineResponse202Index?

    public init() {}

}
