//
// InlineResponse4002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4002: Codable {

    public var documentTypes: InlineResponse400Indexes?

    public init() {}

}
