//
// InlineResponse4006SearchResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4006SearchResults: Codable {

    public var error: String?
    public var metadata: Any?

    public init() {}

}
