//
// InlineResponse400.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse400: Codable {

    public var indexes: InlineResponse400Indexes?

    public init() {}

}
