//
// InlineResponse201Index.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse201Index: Codable {

    public enum Result: String, Codable { 
        case created = "created"
    }
    public var result: Result?

    public init() {}

}
