//
// InlineResponse400Indexes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse400Indexes: Codable {

    public var error: String?

    public init() {}

}
