//
// InlineResponse2007.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2007: Codable {

    public var searchResults: InlineResponse2007SearchResults?

    public init() {}

}
