//
// InlineResponse4001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4001: Codable {

    public var index: InlineResponse400Indexes?

    public init() {}

}
