//
// InlineResponse202Index.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse202Index: Codable {

    public enum Result: String, Codable { 
        case deleted = "deleted"
    }
    public var result: Result?

    public init() {}

}
