//
// InlineResponse4006.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4006: Codable {

    public var searchResults: InlineResponse4006SearchResults?

    public init() {}

}
