//
// InlineResponse4005.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4005: Codable {

    public var document: InlineResponse400Indexes?

    public init() {}

}
