//
// InlineResponse4007.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4007: Codable {

    public var searchResults: InlineResponse4007SearchResults?

    public init() {}

}
