//
// InlineResponse2003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2003: Codable {

    public var documentType: InlineResponse2003DocumentType?

    public init() {}

}
