//
// InlineResponse2004Document.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2004Document: Codable {

    public var result: Any?

    public init() {}

}
