//
// InlineResponse2001Index.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2001Index: Codable {

    public enum Result: String, Codable { 
        case available = "available"
    }
    public var result: Result?

    public init() {}

}
