//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2002: Codable {

    public var indexes: InlineResponse2002Indexes?

    public init() {}

}
