//
// InlineResponse2011.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2011: Codable {

    public var documentType: InlineResponse201Index?

    public init() {}

}
