//
// InlineResponse201.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse201: Codable {

    public var index: InlineResponse201Index?

    public init() {}

}
