//
// InlineResponse4004.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse4004: Codable {

    public var documents: InlineResponse400Indexes?

    public init() {}

}
