//
// SearchSuccess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SearchSuccess: Codable {

    public var searchResults: InlineResponse2007SearchResults?

    public init() {}

}
