//
// SearchFailure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SearchFailure: Codable {

    public var searchResults: SearchFailureSearchResults


    
    public init(searchResults: SearchFailureSearchResults) {
        self.searchResults = searchResults
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(searchResults, forKey: "search_results")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        searchResults = try container.decode(SearchFailureSearchResults.self, forKey: "search_results")
    }
}

