//
// SearchSuccessSearchResultsMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SearchSuccessSearchResultsMetadata: Codable {

    public var numberSearchResults: Double
    public var query: String
    public var aggregated: Any?


    
    public init(numberSearchResults: Double, query: String, aggregated: Any?) {
        self.numberSearchResults = numberSearchResults
        self.query = query
        self.aggregated = aggregated
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(numberSearchResults, forKey: "number_search_results")
        try container.encode(query, forKey: "query")
        try container.encodeIfPresent(aggregated, forKey: "aggregated")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        numberSearchResults = try container.decode(Double.self, forKey: "number_search_results")
        query = try container.decode(String.self, forKey: "query")
        aggregated = try container.decodeIfPresent(Any.self, forKey: "aggregated")
    }
}

