//
// SuggestFailureSuggestResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SuggestFailureSuggestResults: Codable {

    public var error: String
    public var metadata: SuggestFailureSuggestResultsMetadata


    
    public init(error: String, metadata: SuggestFailureSuggestResultsMetadata) {
        self.error = error
        self.metadata = metadata
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(error, forKey: "error")
        try container.encode(metadata, forKey: "metadata")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        error = try container.decode(String.self, forKey: "error")
        metadata = try container.decode(SuggestFailureSuggestResultsMetadata.self, forKey: "metadata")
    }
}

