//
// SuggestQuerySuggest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SuggestQuerySuggest: Codable {

    public var query: String
    public var fields: [String]
    public var fuzzy: Double
    public var size: Double


    
    public init(query: String, fields: [String], fuzzy: Double, size: Double) {
        self.query = query
        self.fields = fields
        self.fuzzy = fuzzy
        self.size = size
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(query, forKey: "query")
        try container.encode(fields, forKey: "fields")
        try container.encode(fuzzy, forKey: "fuzzy")
        try container.encode(size, forKey: "size")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        query = try container.decode(String.self, forKey: "query")
        fields = try container.decode([String].self, forKey: "fields")
        fuzzy = try container.decode(Double.self, forKey: "fuzzy")
        size = try container.decode(Double.self, forKey: "size")
    }
}

